name: MLOps Pipeline

on: [push]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: python src/train.py

      - name: Evaluate model
        run: python src/evaluate.py

      - name: Run tests
        run: pytest tests/

      - name: Build Docker image
        run: docker build -t iris-api .

      - name: Run container
        run: docker run -d -p 8000:8000 iris-api